### PR TITLE
Don't wipe out other association data

### LINKED ISSUE #8: Tweaking to use registry alias / some bugs
Hi @AD7six, I'm starting to use this plugin to see how much more performant it can be with my app (nothing's not translated). I made a commit @ https://github.com/patrickconroy/cakephp-shadow-translate/commit/2e0b133ab1da8b3076c5ca7e2db08d2f0720a487 that attempts to fix how the translation table is set/get in the registry, which was updated in the 3.0 core. Right now my commit almost works, but there are some issues..

```
# VideosTable
$this->addBehavior('ShadowTranslate.ShadowTranslate', [
	'translationTable' => 'VideosTranslations',
	'fields' => ['title', 'description'']
]);
$this->addAssociations([
	'belongsTo' => ['Things']
]);

#VideosController
$video = $this->Videos
	->find('translations')
	->contain(['Things'])
	->firstOrFail();
```

1. In `_addFieldsToQuery`, the ``$query->select($query->repository()->schema()->columns());`` part is wiping out my `Things`. This happens with/without any of my changes applied.

2. `_translations` is always empty on the `Entity` which means you can't do things like ``$video->translation('fr')->title;``. I tried debugging this but can't track it down. Again, this one is with/without my changes.

3. In my commit I'm saving both the translationTable alias and its registryAlias, so when you need those it's in the config. As far as I can tell, the way I have it works, but I'm just making sure I understand what you had in mind for `config['alias']`. Is that supposed to be the translationTable alias? I changed it to wait for `parent::__construct` so your class knows the actual `translationTable`, and take it from that. I also updated your `config['translationTable']` default to be in the format of a `Table` instead of the old-style actual DB table.

At the end of the day I like this method way more than EAV, since each field can be its own type and should use way less `SELECTS`.

### PR DESCRIPTION
**Pull request by AD7six**
Closes #8

### CODE REVIEW

**Comment by patrickconroy** [comment]
Thanks @AD7six, I'm still having some problems in your plugin that I don't have in my fork of it.

1. `_translations` is empty when doing `find('translations')`.
2. `translationTable` is still in the old style, you're not giving anyone the option to customize the datasource. A `TableRegistry::get` of what you have will attempt to get it from `default`, which isn't always correct.
3. It seems like `_addFieldsToQuery` doesn't do what it should. Consider this..
```
$this->Videos
	->find('all')
	->select(['Videos.id'])
	->find('translations')
```
Results in..
```
[id] => 1
    [translation] => 
    [_translations] => Array
        (
        )
```
I made ``if (array_intersect($select, [$field, "$alias.$field"])) {``` always happen, and it does what it should: it adds the translated fields. But I'm not sure what that check is for.

**Comment by AD7six** [comment]
> 1. _translations is empty when doing find('translations').

I don't observe that:

```
-> phpunit
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /home/andy/repos/AD7six/cakephp-shadow-translate/phpunit.xml

........../home/andy/repos/AD7six/cakephp-shadow-translate/tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php (line 305)
########## DEBUG ##########
object(Cake\ORM\Entity) {

	'new' => false,
	'accessible' => [
		'*' => true
	],
	'properties' => [
		'id' => (int) 1,
		'author_id' => (int) 1,
		'title' => 'Title #1',
		'body' => 'Content #1',
		'published' => 'Y',
		'author' => object(Cake\ORM\Entity) {

			'new' => false,
			'accessible' => [
				'*' => true
			],
			'properties' => [
				'id' => (int) 1,
				'name' => 'mariano'
			],
			'dirty' => [],
			'original' => [],
			'virtual' => [],
			'errors' => [],
			'repository' => 'Authors'
		
		},
		'_locale' => 'eng',
		'_translations' => [
			'cze' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'cze',
					'title' => 'Titulek #1',
					'body' => 'Obsah #1'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			},
			'deu' => object(Cake\ORM\Entit
                       ...
```

> 2. translationTable is still in the old style, you're not giving anyone the option to customize the datasource

Can you clarify this point please, I don't follow what you wish to point out.

> 3. It seems like _addFieldsToQuery doesn't do what it should. Consider this..
> $this->Videos
>    ->find('all')
>    ->select(['Videos.id'])
>    ->find('translations')

The following find:
```
        $result = $table
            ->find('all')
            ->select(['Articles.id'])
            ->find('translations')
            ->where(['Articles.id' => 1]) 
            ->firstOrFail();
        debug ($result);
```

Results in :+1: 
```
########## DEBUG ##########
object(Cake\ORM\Entity) {

	'new' => false,
	'accessible' => [
		'*' => true
	],
	'properties' => [
		'id' => (int) 1,
		'_translations' => [
			'cze' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'cze',
					'title' => 'Titulek #1',
					'body' => 'Obsah #1'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			},
			'deu' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'deu',
					'title' => 'Titel #1',
					'body' => 'Inhalt #1'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			},
			'eng' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'eng',
					'title' => 'Title #1',
					'body' => 'Content #1'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			},
			'spa' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'spa',
					'title' => 'First Article',
					'body' => 'Contenido #1'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			},
			'zzz' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'locale' => 'zzz',
					'title' => '',
					'body' => ''
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => 'articles_translations'
			
			}
		]
	],
	'dirty' => [],
	'original' => [],
	'virtual' => [],
	'errors' => [],
	'repository' => 'Articles'

}
###########################
```

Can you please clarify how to reproduce 1. and 3. - and clarify what 2. means?

**Comment by patrickconroy** [comment]
Sorry I missed the notification about this.. I'll make a fresh app today and see if I'm still seeing this.

**Comment by AD7six** [comment]
Sweetness - thanks.

**Comment by patrickconroy** [comment]
OK, so 2. just popped up when making a new app. In your config, you're assuming that the `translationTableAlias` is just a string taken from the table with `Translations` at the end, when it needs to be whatever the actual `alias` is of the actual `translationTable`. For e.g.:

In `VideosTable`
```
$this->addBehavior('ShadowTranslate.ShadowTranslate', [
	'translationTable' => 'VTR',
	'fields' => ['title', 'description', 'youtube_id']
]);
```

The `translationTable` becomes the correct instance of my `VTR` table, but its alias isn't `VideosTranslations`, it's `VTR`. So, when `ShadowTranslate` attempts to get the table from the `TR` via the wrong alias, it uses the wrong connection/table if you've set those in `VTRTable` (I used something deliberately weird, `VTR`, to make sure it's always used.)
If your translationTable is in a plugin, `Foo.VideosTranslations`, it won't be used by your behavior, it will always just assume you meant `VideosTranslations`. This is why in my https://github.com/patrickconroy/cakephp-shadow-translate/commit/2e0b133ab1da8b3076c5ca7e2db08d2f0720a487 I have the behavior wait until after the parent's constructor happens to set the `translationTableAlias`, since that's when the class knows what it actually is.

Also, I still think the `_translationTable()` method is superfluous. `$this->_translationTable` is always going to be your translationTable, since that happens in the parent constructor. It's a little confusing, but if you keep it, it should be

```
protected function _translationTable($config = [])
{
    ...
    return TableRegistry::get(
        $config['translationTableAlias'],
        ['className' => $config['translationTable']] #changed to className
    );
}
```

**Comment by patrickconroy** [comment]
Also, for 1. Your `translationTable` being in the old-style: you have it as a string to the actual DB table, when it needs to be a `className` to a CakePHP `Table`. The core `TranslationTable` uses it that way (``'translationTable' => 'I18n'``), and since `ShadowTranslate` is a subclass, so should this one. It would negate the need for that `_translationTable()` method.

**Comment by AD7six** [comment]
Thanks that info helps, there's some work to do. Some preamble bullet points =):

 * There's no such thing as "old style" - which is why referring to old/new style is confusing. The distinction you've latched onto appears to be "passing a database-table-name to the table registry" (which this behavior has never done) and "passing a class name/alias to the table registry" (which this behavior has always done).
 * `translationTable` (currently) _means_ database table - which is part of the reason with your usage examples it doesn't work. The class and registry alias (boo-boo) is the key `translationTableAlias`.

**Important**: Can you clarify please why you need to explicitly specify the translation table class to use? While it's designed to permit that (because the parent implementation does) - I don't make use of that and didn't expect anyone else to actually use it. Is it, for example, to use the same connection of the translated-table class?

> $this->_translationTable is always going to be your translationTable, since that happens in the parent constructor

Note that the parent constructor doesn't set `_translationTable` - no behavior should be cascade-creating objects - it happens in initialize.

In any event though, this all looks like I have either misread how `translationTable` was used in the parent class, or it changed since the shadow translate behavior was created. Your understanding matches how this class _should_ work - but `translationTableAlias` is the key supposed to permit most of what you're describing.

**Comment by AD7six** [comment]
>  or it changed since the shadow translate behavior was created

[I see what you did there](https://github.com/cakephp/cakephp/commit/2bea4c11637fcb9aef8fe9cb073aff9a6d208493) :trollface:

**Pull request merged**
