### PR TITLE
Updated config

### PR DESCRIPTION
**Pull request by AD7six**
Some other changes afoot too...

### CODE REVIEW

**Comment by ADmad** [comment]
@AD7six On https://coveralls.io/r/AD7six/cakephp-shadow-translate can you please uncheck the "leave comments?" checkbox. That will stop the annoying comments and leave only the status messages.

**Comment by AD7six** [comment]
Whoops. That shiz *is* annoying

**Comment by ADmad** [comment]
Moar aliases!

**Comment by AD7six** [comment]
But thankfully, users only need to care about `translationTable` =)

**Pull request merged**
