### PR TITLE
strict warning on arguments not matching on beforesave

### PR DESCRIPTION
**Pull request by mrnnn**
typehinting has changed in the cakephp core. this fixes the strict warning you get there.

### CODE REVIEW

**Comment by ADmad** [comment]
@mrnnn You need to update the `use` statement above the class too.

**Comment by AD7six** [comment]
Thanks - I'll make a release.

**Comment by mrnnn** [comment]
Slightly ashamed that it took me 3 commits to change this, haha.

**Comment by ADmad** [comment]
@mrnnn In future you can use `git rebase` to squash the commits into one and hide your shame :)

**Pull request merged**
